name: Deploy ADF LinkedService

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string

jobs:
 deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Verify Azure secrets
      run: |
        echo "Client ID: ${{ secrets.AZURE_CLIENT_ID_D_APIM }}"
        echo "Subscription ID: ${{ secrets.AZURE_SUBSCRIPTION_ID_D_APIM }}"
        echo "Tenant ID: ${{ secrets.AZURE_TENANT_ID_D_APIM }}"

    - name: Print Azure Credentials
      run: |
        echo "clientId: ${{ secrets.AZURE_CLIENT_ID_D_APIM }}"
        echo "clientSecret: ${{ secrets.AZURE_CLIENT_SECRET_D_APIM }}"
        echo "tenantId: ${{ secrets.AZURE_TENANT_ID_D_APIM }}"
        echo "subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID_D_APIM }}"

    - name: Log in to Azure
      uses: azure/login@v2
      with:
        creds: |
          {
            "clientId": "${{ secrets.AZURE_CLIENT_ID_D_APIM }}",
            "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET_D_APIM }}",
            "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID_D_APIM }}",
            "tenantId": "${{ secrets.AZURE_TENANT_ID_D_APIM }}"
          }
        auth-type: 'SERVICE_PRINCIPAL'
        enable-AzPSSession: true

    - name: Install jq
      run: sudo apt-get install jq

    - name: Read linkedService JSON files and deploy
      run: |
        linkedService1=$(cat ./linkedService/AzureBlobStorage1.json)
        linkedService2=$(cat ./linkedService/AzureBlobStorage333.json)

        linkedServices=$(jq -n \
          --arg linkedService1 "$linkedService1" \
          --arg linkedService2 "$linkedService2" \
          '[
            {
              "name": "AzureBlobStorage1",
              "definition": $linkedService1 | fromjson
            },
            {
              "name": "AzureBlobStorage333",
              "definition": $linkedService2 | fromjson
            }
          ]')

        az deployment group create \
          --resource-group "komatsu" \
          --template-file ./bicep/modules/linkedservice.bicep \
          --parameters dataFactoryName=ADF-components \
          --parameters linkedServices="$linkedServices"